<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Scenario: Add Inventory with wrong input it will catch an exception" tests="3" skipped="0" failures="0" errors="0" timestamp="2022-02-12T06:52:18" hostname="DESKTOP-5B35QQB" time="0.001">
  <properties/>
  <testcase name="Given an empty recipe book" classname="Scenario: Add Inventory with wrong input it will catch an exception" time="0.0"/>
  <testcase name="When user add inventory with wrong input it will catch an exception" classname="Scenario: Add Inventory with wrong input it will catch an exception" time="0.0"/>
  <testcase name="classMethod" classname="Scenario: Add Inventory with wrong input it will catch an exception" time="0.001"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
